/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#faf9f8',
        error: '#ba1a1a',
        errorContainer: '#ffdad6',
        inverseOnSurface: '#f1f0ef',
        inversePrimary: '#a3c9ff',
        inverseSurface: '#2f3130',
        onBackground: '#1a1c1c',
        onError: '#ffffff',
        onErrorContainer: '#93000a',
        onPrimary: '#ffffff',
        onPrimaryContainer: '#ffffff',
        onPrimaryFixed: '#001c39',
        onPrimaryFixedVariant: '#004883',
        onSecondary: '#ffffff',
        onSecondaryContainer: '#007306',
        onSecondaryFixed: '#002200',
        onSecondaryFixedVariant: '#005303',
        onSurface: '#1a1c1c',
        onSurfaceVariant: '#404752',
        onTertiary: '#ffffff',
        onTertiaryContainer: '#ffffff',
        onTertiaryFixed: '#311300',
        onTertiaryFixedVariant: '#743500',
        outline: '#717783',
        outlineVariant: '#c0c7d4',
        primary: '#005faa',
        primaryContainer: '#0078d4',
        primaryFixed: '#d3e3ff',
        primaryFixedDim: '#a3c9ff',
        secondary: '#006e06',
        secondaryContainer: '#91f77e',
        secondaryFixed: '#94fa81',
        secondaryFixedDim: '#79dd68',
        surface: '#faf9f8',
        surfaceBright: '#faf9f8',
        surfaceContainer: '#efeeed',
        surfaceContainerHigh: '#e9e8e7',
        surfaceContainerHighest: '#e3e2e1',
        surfaceContainerLow: '#f4f3f2',
        surfaceContainerLowest: '#ffffff',
        surfaceDim: '#dadad9',
        surfaceTint: '#0060ab',
        surfaceVariant: '#e3e2e1',
        tertiary: '#974700',
        tertiaryContainer: '#bc5b00',
        tertiaryFixed: '#ffdbc8',
        tertiaryFixedDim: '#ffb689'
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0px 8px 32px rgba(0, 0, 0, 0.04)',
      }
    },
  },
  plugins: [],
}
